### ISSUE TITLE
Program only generates a output.txt

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [ggrrin/DungeonMaster#1]
Hello.

Compiling program and running project DungeonMaster on today's `experimental` branch labelled "release candidate" only generates a `output.txt` file. What's up?

**Comment by ggrrin** [comment]
Hi,

you've run wrong project. You have to build and run DungeonMasterEngine project. It should be hopefully always as default now.

P.S. DungeonMasterParser project is just helper assembly for parsing DUNGEON.DAT file which contains level information.
